### ISSUE TITLE
Non-whitespace before first tag

### ISSUE THREAD

**Issue by benrr101** [Microsoft/vscode-spell-check#63]
I'm consistently getting this error thrown in my debug console shortly after startup when running the extension hosting. 

Extension Version: 0.9.1 (using en language)
VSCode Version: 1.8.1
Operating System: Windows 10 x64

Error message:
```
Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: A
    at error (C:\Users\[user]\.vscode\extensions\seanmcbreen.Spell-0.9.1\node_modules\sax\lib\sax.js:667:10)
    at strictFail (C:\Users\[user]\.vscode\extensions\seanmcbreen.Spell-0.9.1\node_modules\sax\lib\sax.js:693:7)
    at beginWhiteSpace (C:\Users\[user]\.vscode\extensions\seanmcbreen.Spell-0.9.1\node_modules\sax\lib\sax.js:967:7)
    at Object.write (C:\Users\[user]\.vscode\extensions\seanmcbreen.Spell-0.9.1\node_modules\sax\lib\sax.js:1019:11)
    at Parser.exports.Parser.Parser.parseString (C:\Users\[user]\.vscode\extensions\seanmcbreen.Spell-0.9.1\node_modules\xml2js\lib\xml2js.js:145:29)
    at Parser.__bind [as parseString] (C:\Users\[user]\.vscode\extensions\seanmcbreen.Spell-0.9.1\node_modules\xml2js\lib\xml2js.js:3:63)
    at Request._callback (C:\Users\[user]\.vscode\extensions\seanmcbreen.Spell-0.9.1\out\features\callATD.js:22:16)
    at Request.init.self.callback (C:\Users\[user]\.vscode\extensions\seanmcbreen.Spell-0.9.1\node_modules\request\main.js:118:22)
    at Request.<anonymous> (C:\Users\[user]\.vscode\extensions\seanmcbreen.Spell-0.9.1\node_modules\request\main.js:459:16)
    at emitOne (events.js:96:13)
```

Repro Steps:
- Be in an extension project
- Start the extension from the debug pane, wait for extension hosting environment to start
- Open the debug console, find error message from above

**Comment by marcduiker** [comment]
I'm getting the exact same error. Also using 0.9.1 on VSCode 1.8.1.

My spell.json:
`{
    "language": "en",
    "ignoreWordsList": [],
    "mistakeTypeToStatus": {
        "Spelling": "Error",
        "Passive voice": "Hint",
        "Complex Expression": "Disable",
        "Hidden Verbs": "Information",
        "Hyphen Required": "Disable",
        "Redundant Expression": "Disable",
        "Did you mean...": "Disable",
        "Repeated Word": "Warning",
        "Missing apostrophe": "Warning",
        "Cliches": "Disable",
        "Missing Word": "Disable",
        "Make I uppercase": "Warning"
    },
    "languageIDs": [
        "markdown",
        "plaintext"
    ],
    "ignoreRegExp": [
        "/\\(.*\\.(jpg|jpeg|png|md|gif|JPG|JPEG|PNG|MD|GIF)\\)/g",
        "/((http|https|ftp|git)\\S*)/g"
    ]
}`

**Comment by cfjedimaster** [comment]
To add to it - it also seems as if it is no longer spellchecking either. That's probably obvious, but didn't see it mentioned above.

**Comment by seanmcbreen** [comment]
This extension has had a large number of [stability issues based on the availability of the underlying service](https://github.com/Microsoft/vscode-spell-check/issues/54).  Today I published an update which points users to [another extension for Spell Checking](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

I'm closing the majority of issues as development on the extension has stopped. Sorry for any inconvenience this caused anyone, the good news is that there are better options out there now that don't require the service.

Sean
